### ISSUE TITLE
no words shown in firefox

### ISSUE THREAD

**Issue by eskoONE** [ranelpadon/ngram-type#1]
https://i.imgur.com/KdrgiGa.png

would be nice if you could add firefox support.

**Comment by ranelpadon** [comment]
Really? Im using Firefox Developer Edition, and this was my screenshot captured earlier:
<img width="1439" alt="Screen Shot 2020-10-26 at 9 09 45 AM" src="https://user-images.githubusercontent.com/4292088/97127322-44a15100-1774-11eb-8848-c52bd8ab043d.png">

Have your tried clicking the other Ngram source and/or updating the Combination/Repetition settings? Since those will trigger lesson updates. Will try to replicate also your issue. Let me know if you still have issues.

Thanks for your feedback

**Comment by ranelpadon** [comment]
I've tried it also now in the latest Firefox for Mac:
<img width="1440" alt="Screen Shot 2020-10-26 at 10 21 15 AM" src="https://user-images.githubusercontent.com/4292088/97127618-12442380-1775-11eb-99fd-6ee174b00187.png">

Looks ok also. Do you have custom settings in your Firefox regarding Local Storage, site data, cookies, etc? I'm thinking if they interfere. Please check also if there are browser console errors and send it to me. And kindly check also in other browsers in your end, to narrow down your issue.

**Comment by ranelpadon** [comment]
Tried it in Brave browser and I could see your issue, it's Chromium-based though, will investigate:
<img width="1440" alt="Screen Shot 2020-10-26 at 10 24 39 AM" src="https://user-images.githubusercontent.com/4292088/97127805-95657980-1775-11eb-9930-7481d7225756.png">

**Comment by ranelpadon** [comment]
Ah I see, because I have a similar Local Storage `data` named "data" in Brave which were created when I used my other project before:
https://ranelpadon.github.io/keyzen-colemak-dh/

Hence, they're colliding with each other. So, not really a browser issue, but collision w/ other projects hosted in GitHub Pages since there should be one "data" only in this site/domain. Will rename my project data then to be more specific and avoid collision w/ other projects. Will be quick to fix.

**Comment by ranelpadon** [comment]
@eskoONE Fixed it now, should have no collision now w/ other projects in GitHub IO:
<img width="1439" alt="Screen Shot 2020-10-26 at 10 42 13 AM" src="https://user-images.githubusercontent.com/4292088/97128715-03ab3b80-1778-11eb-932b-2646d5119ae5.png">

Please check. Thanks :)

**Comment by eskoONE** [comment]
sry for replying so late. seems like you solved the issue on your own already and it seems to be working now. thanks a lot!

**Comment by ranelpadon** [comment]
@eskoONE Yeah, I added numerous fixes/improvements also, so it's much more stable now, and easier to use. Let me know if you have suggestions/pain points.

Currently, I'm practicing everyday with my 2 projects only:
1. Familiarize w/ the letter placements in general (didn't care about numbers/capital letters/punctuation for now)
- https://ranelpadon.github.io/keyzen-colemak-dh/
2. Practice on common letter sequences/words
- https://ranelpadon.github.io/ngram-type/

These 2 tools complement with each other, I've been using them for weeks now, and my improvements are drastic. If you care about the `MonkeyType` (MT) stats, then your main focus is the Top 200 words since they use those exact words in their tests. But bigrams/trigrams are really useful in general, for Top 200 words or those outside of it. Quadgrams/Top 50 words are optional/secondary goals I think. Will continue using these tools also in the coming weeks/months and will check my MT stats also maybe every week. :)
