### ISSUE TITLE
[Question] Source of data (I'd love more n-grams!)

### ISSUE THREAD

**Issue by johnolek** [ranelpadon/ngram-type#11]
Hello!

First of all thank you so much for creating this valuable tool. It's helped me a great deal in my quest to learn colemak, potentially even saving me from giving up!

I was wondering if you could share the source you're using for n-grams of various lengths, specifically because I'm interested in expanding my training to the top 100 or 200 tri, tetra, and pentagrams.

Thanks again!

**Comment by xsrvmy** [comment]
Not sure what this website uses, but on norvig's ngram page there is a download for ngram frequency for n = 1 to 9

**Comment by ranelpadon** [comment]
@johnolek Yep, [Peter Norvig](https://en.wikipedia.org/wiki/Peter_Norvig)'s corpus is my main source. He works at Google that's why he has access to Google data and stuff. This is my main source (which contains also Norvig's motivation of his list):
http://www.norvig.com/mayzner.html

Maybe you could download indeed the full list as per the comment above:
> on norvig's ngram page there is a download for ngram frequency for n = 1 to 9

**Comment by ranelpadon** [comment]
The **Bigrams** ([count_2l.txt](http://norvig.com/ngrams/count_2l.txt) and **Trigrams** ([count_3l.txt](http://norvig.com/ngrams/count_3l.txt)) could be found also here:
http://norvig.com/ngrams/

**Comment by alexpharris** [comment]
A lot of the links on http://www.norvig.com/mayzner.html are broken, but thankfully the zip file containing all the data still works! http://www.norvig.com/tsv/ngrams-all.tsv.zip

**Comment by ranelpadon** [comment]
FYI, closing this since I think I already answered the question. Feel free to re-open if you still have other related concerns. Thanks

**Comment by ranelpadon** [comment]
@johnolek  @xsrvmy FYI, I implemented now the Top 100 n-grams instead of Top 50 n-grams as per https://github.com/ranelpadon/ngram-type/commit/e4ce57461f7ddcef9767044ac749f6c5e69d3633.

Fortunately, I found a good source for the top n-grams which I used also in the `Top 100` implementation:
https://github.com/KaranAgarwalla/Encryption-Decryption
