### ISSUE TITLE
Expand lists so user can practice 100+ most-common ngrams

### ISSUE THREAD

**Issue by theroncross** [ranelpadon/ngram-type#17]
50 is nice, but as soon as you start typing real words, you hit a lot of ngrams that you haven't practiced.

**Comment by ranelpadon** [comment]
@theroncross Thanks for this suggestion. The original idea was from the [The First 20 Hours](https://first20hours.com/) book in which the author used the `Top 50` n-grams mainly due to time constraints, which I referenced also for my own practice. In hindsight, `Top 100` n-grams also make sense since it could improve the overall training. 

Anyway, I implemented it now as per https://github.com/ranelpadon/ngram-type/commit/e4ce57461f7ddcef9767044ac749f6c5e69d3633, just play around with the `Repetition` and/or `Combination` settings to force reset the saved data to use the `Top 100`:

https://ranelpadon.github.io/ngram-type/

<img width="1439" alt="Screen Shot 2022-08-06 at 10 47 16 PM" src="https://user-images.githubusercontent.com/4292088/183254064-34c5da32-8637-46be-b512-0a1a2c395887.png">

Let me know if you have issues. Cheers

CC: @bew

**Comment by theroncross** [comment]
This is great. I think I had to delete my localstorage to get the new ngrams, though I stupidly did that before trying to get to the end of a set.

Thanks again for maintaining what I think is among the best typing trainers around.

**Comment by ranelpadon** [comment]
Glad to hear it. Although in my case, I didn't need to clear my `localStorage`. But yes, clearing the `localStorage` will do it. I was thinking also if I should use the `Top 200` instead of `Top 100`. The Top 100 looks like a good compromise though between too few (Top 50) and too many (Top 200). Or let's see if other users will want to have the Top 200.

One option I think is to have a more dynamic source like being able to choose the Top 50, Top 100, Top 150, or Top 200 n-grams. It would require more thought/effort though and will depend if users will want it. Cheers

**Comment by ranelpadon** [comment]
FYI, closing this since I believe this is now implemented. If other users will show interest in **Top 150** or **Top 200** n-grams later on, I would consider it also. Cheers. :)
