### ISSUE TITLE
App freezes when setting "combination" value

### ISSUE THREAD

**Issue by debashisbiswas** [ranelpadon/ngram-type#31]
Steps to reproduce:

1. Edit "combination" field directly to change the value to empty or any value less than 1. (this is not possible using the arrow keys, because the browser enforces that the minimum value is 1)
2. Observe that the application freezes.

After a quick analysis, I can see that the `generatePhrases` function is getting stuck in an infinite loop unless this value is > 0, but I'm not sure how you'd like to solve this. Maybe stronger validation in the HTML? Let me know and I'd be happy to submit a PR.

**Comment by ranelpadon** [comment]
Thanks for reporting. This would be a rare case though since `0` combination doesn't make sense and users will not likely use this value. But it's a bug indeed when inputting manually and not using arrow keys.

Feel free to submit a PR, then let's see:
> but I'm not sure how you'd like to solve this. Maybe stronger validation in the HTML? Let me know and I'd be happy to submit a PR.

If you could add a validator in the HTML it would be great. Otherwise, I think we would add a validator in the Vue layer. :)
