### ISSUE TITLE
Pangram/Custom

### ISSUE THREAD

**Issue by nkabbara** [ranelpadon/ngram-type#7]
Hello!

When I click on the custom link, nothing is happening. Am I supposed to get a dialogue to input text? I tried on chrome and firefox.

**Comment by ranelpadon** [comment]
Yeah, I noticed it also recently, but I thought it was just due to my browser caching. I think it was broken at some point, and I just didn't notice. I'll fix it asap (most likely this weekend). Thanks for reporting the issue.

**Comment by nkabbara** [comment]
Thank you very much!

While using keybr.com I noticed a couple of bigrams (er and re) that are
problematic for me. I swap them. ie. Instead of typing er, I type re and
vice versa. But mostly happens in those bigrams, not when e and r are with
different letters.

So my plan was to feed these into custom and have it train me :)

**Comment by ranelpadon** [comment]
@nkabbara Fixed it now as per https://github.com/ranelpadon/ngram-type/commit/311d5e2595f4133149d7acf6ffc37d10a4a9dd72.

Apparently, I used **Bootstrap 4** before using this link (which always point to latest version):
https://bootswatch.com/_vendor/bootstrap/dist/js/bootstrap.bundle.min.js

But now it points to **Bootstrap 5**! So, just pointed to correct/previous version:
https://bootswatch.com/4/_vendor/bootstrap/dist/js/bootstrap.bundle.min.js

That's why I'm puzzled also why it's not working at some point even though I don't have code changes related to it.

Live screenshot:

<img width="1440" alt="Screen Shot 2022-01-07 at 5 24 25 PM" src="https://user-images.githubusercontent.com/4292088/148522553-b26396ed-7367-40f8-ae96-e6e4ea1c5336.png">

Please verify. Cheers

**Comment by nkabbara** [comment]
Thank you sir! Verified and works great!

**Comment by ranelpadon** [comment]
Nice! Will close this issue now. Thanks :)
